name: Bug Report
description: Report a bug on eFront
title: "[Bug] <short description of the bug>"
labels: ["Bug"]
assignees: 
  - MisterIcy
  - 4riS
body: 
  - type: markdown
    attributes:
      value: | 
        ## 🐞 Bug Report
        Please fill in the following details to help us understand the issue you are facing.
        Incomplete reports may be delayed.
  - type: input
    id: version
    attributes:
      label: eFront Version
      description: |
        Provide the version of eFront where the bug is occurring.
        
        **Note**: Versions prior to 7.0.0 are no longer supported. Please confirm that the issue exists on a supported version before reporting.
      placeholder: 7.0.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: |
        A clear and concise description of what the bug is.
      placeholder: |
        I am unable to add a new user in eFront.
        When I click on the "Add User" button, the page does not load.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: |
        Provide a **step-by-step** guide on how to reproduce the issue.  
        Include any specific configurations or settings that are relevant to the bug:
        - Browser version, if the issue is browser-specific
        - Operating system, if the issue only occurs on certain OSes
        - Server configuration (e.g. PHP version, MariaDB version), if relevant
      placeholder: |
        1. Login as an Administrator
        2. Go to the Users Page
        3. Click on the "Add User" button.
        4. Notice that the page does not load
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: |
        Describe what you expected to happen when following the steps above.
      placeholder: |
        The page should load and allow me to add a new user.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: |
        Describe what actually happened when following the steps above.
      placeholder: |
        The page does not load and I see a blank screen.
    validations:
      required: true
  - type: textarea
    id: visualproof
    attributes:
      label: Visual Proof (optional)
      description: |
        If applicable, please provide a screenshot or screen recording of the issue. 
        This will help us better understand the problem and facilitate a quicker reproduction and resolution.
      placeholder: |
        Drag and drop a screenshot or screen recording here (optional).
    validations:
      required: false
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is the issue?
      options: 
        - 💥 Critical – Crashing eFront / Blocking usage
        - 🐛 Major – Key functionality is not working
        - 🧩 Minor – Does not affect core functionality
        - 🧪 Cosmetic – UI/UX/Translations issues
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Final Checklist
      options:
        - label: I have searched existing issues and this bug has not been reported before.
          required: true
        - label: I have checked the documentation and found no mention of this issue.
          required: true
        - label: I have disabled all plugins and removed any custom JavaScript and the issue still occurs.
          required: true
        - label: I have provided all necessary details to reproduce the issue.
          required: true
